### ISSUE TITLE
Can't see some translations in game.

### ISSUE THREAD

**Issue by SkipperSkip** [WarFollowsMe/TranslationMod#13]
When I try to translate these lines in Menus.json it doesn't show up in game.

"Favorite@newlineThing"
"Animal@newlinePreference"
"Farm@newlineName"

![2](https://cloud.githubusercontent.com/assets/20422157/21960319/80808cd8-daef-11e6-843b-0317055a22cd.png)
![1](https://cloud.githubusercontent.com/assets/20422157/21960321/825aac3c-daef-11e6-834a-8923dfd0200e.png)

**Comment by warfollowsme** [comment]
Do you have created your own language pack?

**Comment by SkipperSkip** [comment]
Yes I did create a new language pack. Is this tool compatible with newest update? Because these are not the only translations that I can't see in game.

**Comment by SkipperSkip** [comment]
@WarFollowsMe Is there a solution?

**Comment by SkipperSkip** [comment]
@WarFollowsMe  will you answer?

**Comment by warfollowsme** [comment]
Sorry for late answer. No, this tool not compatible with newest update.

**Comment by SkipperSkip** [comment]
Are you planning to make it compatible? Because it would be nice if you can. We want to translate it into Turkish. Which will not be in game even after the language update at February. So this tool is our only hope to play Stardew Valley in our language.

**Comment by Marcello97** [comment]
@WarFollowsMe I will be eternally grateful if you update the tool to latest version of game :smile: 
I'm planning to translate the game into italian language ( since the dev will not release an italian localization) and you are my only chance.

**Comment by SkipperSkip** [comment]
Please answer @WarFollowsMe

**Comment by warfollowsme** [comment]
My suggestion to you guys it's just wait until official localization came out. I think (looking on the long list of available languages), the game will have more or less universal tool to add other languages by community. As for me, unfortunately I don't have time to work in this project. Good luck.
