### ISSUE TITLE
Официальный перевод Stardew Valley

### ISSUE THREAD

**Issue by ghost** [WarFollowsMe/TranslationMod#15]
Здравствуйте!
Я так понимаю что работа над русификатором заморожена.
В проект вложено много сил и часов.
Официальная локализация очень плохая, и было бы замечательно видеть вашу работу официально в игре. А если предложить воспользоваться какими-то вашими наработками разработчикам?
По всей видимости, помощь им действительно не помешает, - это заметно по шрифтам и литературности перевода.
Возможно даже можно сделать им деловое предложение.
Даже если у них появится желание использовать вашу работу, они не смогут сделать это просто так. Для них важна и юридическая составляющая.
Просто обидно если ваш труд "уйдет в небытие", ему явно место в официальном релизе.
В общем стоит закинуть удочку, а?
Для связи с издателями:
contact@chucklefish.org
tom@chucklefish.org

**Comment by warfollowsme** [comment]
Мы еще на ранней стадии связывались с разработчиками, но от них контакта не последовало. Так же мы выкладывали на официальном форуме новость о некоторых результатах нашей работы. Так же отклика не последовало. Когда объявили о официальной локализации, мы понадеялись, что разработчики возьмут хотя бы наш концепт. Мы делали проект открытыми с акцентом на возможность другим людям добавлять новые языки самостоятельно. К сожалению и эти наши надежды не оправдались. Заниматься чем-либо без поддержки очень утомительно и мы потеряли к проекту интересен. Но все наработки открыты. Если кому-то интересно пусть пользуется. Нам не жалко.

**Comment by ghost** [comment]
Я понял вас. Это очень здорово, что вы открыты.
Боюсь, что они боятся именно юридических последствий, даже малейших рисков. То есть они не могут просто так взять вашу работу и использовать в своем продукте, даже если им предлагают "просто так".
Им нужно будет получить от вас письменное разрешение, консультироваться с юристами, изучать вопрос законодательства, где проживает помощник и так далее.
Возможно стоит связаться еще раз, сделав акцент на юридической составляющей?

Простите мою навязчивость, просто я читаю сообщения издателей и смотря на локализацию, делаю вывод, что игру в принципе переводят не носители языка, до чего смешны ошибки. Они даже не замечают что в шрифте одна буква намного выше всех остальных (очевидно видят кириллицу в первый раз), про перевод слов транскрипцией вообще молчу... просто бомбит.

**Comment by warfollowsme** [comment]
Если хотите можете связаться с ними от нашего имени.

**Comment by ghost** [comment]
Я связывался, но конечно не от вашего имени.
Они знают,  что есть ваша модификация, это факт. Но использовать не хотят, даже частично, и причины не называют.
Буду пробовать еще, спасибо за обратную связь!
